### ISSUE TITLE
Fix Raia_CancerResearch2011

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2238]
Importing Raia_CancerResearch2011 fails since https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/pull/197

e.g. https://github.com/AMICI-dev/AMICI/actions/runs/7207106512/job/19633280668
```
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp: In function ‘void amici::model_Raia_CancerResearch2011::sigmay_Raia_CancerResearch2011(amici::realtype*, amici::realtype, const realtype*, const realtype*, const realtype*)’:
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:17:102: error: ‘CD274mRNA’ was not declared in this scope
   17 |     sigma_observable_CD274mRNA__scaling_CD274mRNA__sd_CD274mRNA_abs_sd_CD274mRNA_rel__model1_data1 = CD274mRNA*noiseParameter2_observable_CD274mRNA__scaling_CD274mRNA__sd_CD274mRNA_abs_sd_CD274mRNA_rel__model1_data1*observableParameter1_observable_CD274mRNA + noiseParameter1_observable_CD274mRNA__scaling_CD274mRNA__sd_CD274mRNA_abs_sd_CD274mRNA_rel__model1_data1;  // sigmay[0]
      |                                                                                                      ^~~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:19:357: error: ‘IL13_DecoyR’ was not declared in this scope
   19 |     sigma_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 = noiseParameter1_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 + noiseParameter2_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1*observableParameter1_observable_IL13_cell*(IL13_DecoyR + IL13_Rec + p_IL13_Rec + p_IL13_Rec_i);  // sigmay[2]
      |                                                                                                                                                                                                                                                                                                                                                                     ^~~~~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:19:371: error: ‘IL13_Rec’ was not declared in this scope
   19 |     sigma_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 = noiseParameter1_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 + noiseParameter2_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1*observableParameter1_observable_IL13_cell*(IL13_DecoyR + IL13_Rec + p_IL13_Rec + p_IL13_Rec_i);  // sigmay[2]
      |                                                                                                                                                                                                                                                                                                                                                                                   ^~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:19:382: error: ‘p_IL13_Rec’ was not declared in this scope
   19 |     sigma_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 = noiseParameter1_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 + noiseParameter2_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1*observableParameter1_observable_IL13_cell*(IL13_DecoyR + IL13_Rec + p_IL13_Rec + p_IL13_Rec_i);  // sigmay[2]
      |                                                                                                                                                                                                                                                                                                                                                                                              ^~~~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:19:395: error: ‘p_IL13_Rec_i’ was not declared in this scope
   19 |     sigma_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 = noiseParameter1_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1 + noiseParameter2_observable_IL13_cell__scaling_IL13_cell__sd_IL13_cell_abs_sd_IL13_cell_rel__model1_data1*observableParameter1_observable_IL13_cell*(IL13_DecoyR + IL13_Rec + p_IL13_Rec + p_IL13_Rec_i);  // sigmay[2]
      |                                                                                                                                                                                                                                                                                                                                                                                                           ^~~~~~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:29:102: error: ‘SOCS3mRNA’ was not declared in this scope
   29 |     sigma_observable_SOCS3mRNA__scaling_SOCS3mRNA__sd_SOCS3mRNA_abs_sd_SOCS3mRNA_rel__model1_data1 = SOCS3mRNA*noiseParameter2_observable_SOCS3mRNA__scaling_SOCS3mRNA__sd_SOCS3mRNA_abs_sd_SOCS3mRNA_rel__model1_data1*observableParameter1_observable_SOCS3mRNA + noiseParameter1_observable_SOCS3mRNA__scaling_SOCS3mRNA__sd_SOCS3mRNA_abs_sd_SOCS3mRNA_rel__model1_data1;  // sigmay[12]
      |                                                                                                      ^~~~~~~~~
/home/runner/work/AMICI/AMICI/test_bmc/Raia_CancerResearch2011/sigmay.cpp:33:304: error: ‘pJAK2’ was not declared in this scope
   33 |     sigma_observable_pJAK2__scaling_pJAK2__sd_pJAK2_abs_sd_pJAK2_rel__model1_data2 = noiseParameter1_observable_pJAK2__scaling_pJAK2__sd_pJAK2_abs_sd_pJAK2_rel__model1_data2 + noiseParameter2_observable_pJAK2__scaling_pJAK2__sd_pJAK2_abs_sd_pJAK2_rel__model1_data2*observableParameter1_observable_pJAK2*pJAK2;  // sigmay[16]
      |                                                                                                                                                                                                                                                                                                                ^~~~~
```

Problem in AMICI or in the PEtab problem?

**Comment by dweindl** [comment]
See also #609 #919

Seems like my workaround from https://github.com/AMICI-dev/AMICI/pull/1791 doesn't handle this case properly.

**Comment by dweindl** [comment]
> Seems like my workaround from #1791 doesn't handle this case properly.

Breaks `petab.flatten_timepoint_specific_output_overrides(petab_problem)` breaks it.

**Comment by dweindl** [comment]
Will be fixed in the next libpetab release by https://github.com/PEtab-dev/libpetab-python/pull/235, closing here.
