### ISSUE TITLE
cblas.h not found when installing on ubuntu 20.04.1

### ISSUE THREAD

**Issue by TeaWolf** [AMICI-dev/AMICI#1602]
I've had no problem installing amici on my OSX laptop, but no go on my Ubuntu desktop 
Using  the following commands as per the [documentation](https://amici.readthedocs.io/en/v0.11.15/python_installation.html).

```
sudo apt install libatlas-base-dev swig
sudo apt install libhdf5-serial-dev
pip install amici 
```

I get the following inclusion error.

```
 amici/src/cblas.cpp:16:13: fatal error: cblas.h: No such file or directory
     16 |    #include <cblas.h>
        |             ^~~~~~~~~
  compilation terminated.
  error: command '/home/llamagod/miniconda3/envs/rjmcmc_thesis/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for amici
```

I see that there's an [issue](https://github.com/AMICI-dev/AMICI/issues/781) open talking about making this more flexible.

Is there some kind of fix that I could apply at the moment however?

**Comment by TeaWolf** [comment]
I'm unfamiliar with locate so I used find
```
find /usr -name '*blas*.h'
/usr/include/x86_64-linux-gnu/cblas.h
/usr/include/x86_64-linux-gnu/cblas-atlas.h
/usr/include/x86_64-linux-gnu/f77blas.h
/usr/include/x86_64-linux-gnu/cblas-openblas.h
/usr/include/x86_64-linux-gnu/openblas_config.h
/usr/include/x86_64-linux-gnu/openblas-pthread/cblas.h
/usr/include/x86_64-linux-gnu/openblas-pthread/f77blas.h
/usr/include/x86_64-linux-gnu/openblas-pthread/openblas_config.h
```

The file you mention does seem to be there though

**Comment by dweindl** [comment]
> The file you mention does seem to be there though

That's funny. Could you please post the full output of `pip install -v amici`?

**Comment by dweindl** [comment]
Ah. I think the issue is that you are installing AMICI inside a conda environment. This does not use the regular include directories, and therefore, does not find `/usr/include/x86_64-linux-gnu/cblas.h`.  

Does AMICI installation succeed after `conda install -c anaconda openblas`?

**Comment by dweindl** [comment]
> Does AMICI installation succeed after `conda install -c anaconda openblas`?

You will probably have to set some additional environment variable during AMICI installation and when importing models: 
`export BLAS_LIBS=-lopenblas`.

**Comment by TeaWolf** [comment]
Yes sorry it is a conda environment, forgot to mention it.

The combination of 
```
conda install -c conda-forge openblas
export BLAS_LIBS=-lopenblas
pip install amici
``` 
Does the trick.

However my conda environment seemed to have an openblas in it before
```
# Present before conda install -c conda-forge openblas
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
# Present after conda install -c conda-forge openblas
openblas                  0.3.18          pthreads_h4748800_0    conda-forge
```
Not sure why the other one wasn't doing it.

**Comment by dweindl** [comment]
> Does the trick.

Great.

> Not sure why the other one wasn't doing it.

The issue was only the missing `BLAS_LIBS=-lopenblas` then. We will add that to the documentation. 
Keep in mind, that you will have to have that set also when import any models.

**Comment by TeaWolf** [comment]
well I actually tried BLAS_LIBS=-lopenblas before installing the openblas from conda forge just to see if it would work, but it failed with the same error.

**Comment by dweindl** [comment]
Ah, yes, it seems  `libopenblas` only contains the library, but not the header files.

**Comment by TeaWolf** [comment]
ah so that's it then!

**Comment by winkmal** [comment]
Sorry to reopen this again, but I got the same error message during installation with `pip`:
`amici/src/cblas.cpp:16:13: fatal error: cblas.h: No such file or directory`

It's an Alma Linux 8.7 system, and `blas` is installed. (I only have user access, no root privileges.)
```bash
$ yum list installed | grep blas
blas.x86_64                                       3.8.0-8.el8                              @appstream
blas-devel.x86_64                                 3.8.0-8.el8                              @powertools
openblas-openmp.x86_64                            0.3.15-4.el8                             @powertools
openblas-srpm-macros.noarch                       2-2.el8                                  @appstream
```

The output of the commands you mentioned give:

```bash
$ locate  /usr/*cblas*.h
$ find /usr -name '*blas*.h'
find: ‘/usr/share/polkit-1/rules.d’: No permission
find: ‘/usr/share/selinux/targeted/default/active’: No permission
/usr/include/cblas/cblas.h
/usr/include/cblas/cblas_f77.h
/usr/include/cblas/cblas_mangling.h
/usr/include/cblas/cblas_test.h
find: ‘/usr/libexec/initscripts/legacy-actions/auditd’: No permission
find: ‘/usr/libexec/warewulf/cgi-bin’: No permission
```
Any idea what else I could try?

**Comment by dweindl** [comment]
Hi @winkmal, does 
```bash
BLAS_CFLAGS="$(pkg-config --cflags blas)" BLAS_LIBS="$(pkg-config --libs blas)" pip install amici 
```
work?

**Comment by winkmal** [comment]
> Does locate /usr/*cblas.a show anything?

No, nothing.

I tried:
```bash
BLAS_CFLAGS="-I/usr/include/cblas/" BLAS_LIBS="-lblas" pip3 install --user amici --upgrade
```
Now, I get a different error message:
```bash
amici/amici_wrap.cxx:174:11: fatal error:  Python.h: No such file or directory
# include <Python.h>
             ^~~~~~~~~~
```
As a sidenote, I could get AMICI to install and work on an Ubuntu 22.04 based Linux system (Python 3.10.6 via `apt`). The missing library error(s) are specific to this Alma Linux system.

**Comment by dweindl** [comment]
> amici/amici_wrap.cxx:174:11: fatal error: Python.h: No such file or directory

It looks like python header files are not installed by default on your system (or at least not in a default location). On Ubuntu, they come in the `python3-dev` package, on CentOS `python-devel`. Are you able to install that? 

If you can't use yum to install that, it's somewhat inconvient: You'll have to download that manually, unpack it, and set environment variable `LDFLAGS` to `-L${absolute_path_to_directory_containing_Python.h}`.
